repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.4.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.19.2
  hooks:
    - id: check-github-workflows
    - id: check-readthedocs
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
    - id: black
      name: "Autoformat python files"
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
    - id: blacken-docs
      additional_dependencies: ['black==22.10.0']
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      name: "Lint python files"
      additional_dependencies:
        - 'flake8-bugbear==22.10.27'
        - 'flake8-comprehensions==3.10.1'
        - 'flake8-typing-as-t==0.0.3'
- repo: https://github.com/PyCQA/isort
  rev: 5.11.0
  hooks:
    - id: isort
      name: "Sort python imports"
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
    - id: pyupgrade
      args: ["--py36-plus"]

# custom local hooks
- repo: local
  hooks:
    - id: generate-init
      name: "Check generated __init__.py"
      entry: ./src/globus_sdk/_generate_init.py
      language: python
      always_run: true
      pass_filenames: false
