version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - bash ./scripts/rtd-pre-sphinx-build.sh

python:
  install:
    - method: pip
      path: .
    - requirements: "requirements/py3.11/docs.txt"
